FROM public.ecr.aws/docker/library/node:16-alpine as setup
WORKDIR /usr/src/backend
COPY --chown=node:node . .
COPY --chown=node:node package.json yarn.lock ./
RUN npm install --no-progress

EXPOSE 3001
USER node

# 起動
CMD ["npm","run", "dev"]
