FROM public.ecr.aws/docker/library/node:20-alpine3.17 as setup
WORKDIR /usr/src/backend
COPY --chown=node:node . .
COPY --chown=node:node package.json yarn.lock ./
RUN yarn install --no-progress
RUN npm install -g @nestjs/cli
RUN npx prisma generate

EXPOSE 3001
USER node

# 起動
CMD ["yarn", "start:dev"]
